---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
        url: ${CF_TARGET_URL}
        organization: ${CF_ORGANIZATION}
        space: ${CF_SPACE}
        application: smsss
    script: |-
      #!/bin/bash
      cf push --random-route "${CF_APP}"

      # View logs
      #cf logs "${CF_APP}" --recent
